### ISSUE TITLE
Questions for Ilana & Ali

### ISSUE THREAD

**Issue by amj133** [amj133/bike-share#46]

**Comment by amj133** [comment]
+ There are a few missing data points in the weather csv, should we fill these with dummy data, or take the validations off of our model?
+ Also, I tried seeding last night, and my computer couldn't do it even over night, should we not be using the whole data set on our local db's? @AliSchlereth

**Comment by AliSchlereth** [comment]
@amj133 I recommend taking validations off those attributes. Dummy data will throw off your calculations.  

I'm checking with Ilana on the second question, but I believe you should be seeding with the whole data set. You'll have to make a small set of fixtures to push it to Heroku though. I'm wondering if you have something off in your seed file?
