### ISSUE TITLE
User Story 22 - Weather Dashboard

### ISSUE THREAD

**Issue by amj133** [amj133/bike-share#56]
good morning - im looking for clarification on user story 22 22                                                                                                    
As a registered user and admin,                                                                                                    
When I visit '/weather-dashboard',                                                                                                    
I see the Breakout of average number of rides, highest number of rides, and lowest number of rides on days with a high temperature in 10 degree chunks (e.g. average number of rides on days with high temps between fifty and sixty degrees)...

Are you looking for average number of rides per day in a given temperature interval (0-9 degrees)(10-19 degrees) etc. @AliSchlereth @icorson3

**Comment by icorson3** [comment]
yes @amj133 it will start with about 30-40 something degrees.

**Comment by AliSchlereth** [comment]
@amj133 I also really like that you included the relevant user story in your question. ✨
